### ISSUE TITLE
Missing commits

### ISSUE THREAD

**Issue by IzzySoft** [Moderpach/Extinguish#1]
It seems the APK at the latest tag was not built from the commit the tag points to – (not only) the `AndroidManifest.xml` differs:

```diff
-      ATTR: http://schemas.android.com/apk/res/android:versionCode=30
-      ATTR: http://schemas.android.com/apk/res/android:versionName='0.9.1'
+      ATTR: http://schemas.android.com/apk/res/android:versionCode=29
+      ATTR: http://schemas.android.com/apk/res/android:versionName='0.9'
```

APK identifies as

    package: name='own.moderpach.extinguish' versionCode='30' versionName='0.9.1'

But your [`build.gradle.kts`](https://github.com/Moderpach/Extinguish/blob/master/app/build.gradle.kts#L21) still says

```kotlin
        versionCode = 29
        versionName = "0.9"
```

Maybe you've built the APK locally and forgot to push the last commits? Or even forgot to commit the last local changes?

**Comment by IzzySoft** [comment]
PS: scanner also reported

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

which can easily avoided with a minor addition to your `build.gradle.kts`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

**Comment by Moderpach** [comment]
thank you reminding me, i'll check it later.

**Comment by IzzySoft** [comment]
Thanks – and congrats, it's RB! So [here comes your welcome toot](https://floss.social/@IzzyOnDroid/113107591622852691):

![image](https://github.com/user-attachments/assets/72a0fcb5-8ace-43f3-aee5-488a07abd83e)

I can confirm that signature block blob being gone. All the scanners report is:

```
- Checking 'repo/own.moderpach.extinguish_31.apk' for libraries and malware …
- Checking the app's AndroidManifest.xml …
! repo/own.moderpach.extinguish_31.apk declares sensitive permission(s): android.permission.SYSTEM_ALERT_WINDOW
```

So could you please tell me what `SYSTEM_ALERT_WINDOW` is used for, so I can add it to the app's "green list" with the proper explanation?

![image](https://github.com/user-attachments/assets/2b991226-2e11-4d1d-9dc6-95bf8125eb29)

**Comment by IzzySoft** [comment]
Thanks!

![image](https://github.com/user-attachments/assets/753a344a-4304-450e-a7e2-62dde080b0bd)

If you want to, explanations can be added to the other permissions as well. That's optional of course. So if you want it, just give me a list – otherwise, all is set now :smiley:

**Comment by IzzySoft** [comment]
Oh, PS: be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to [Extinguish at IzzyOnDroid](https://apt.izzysoft.de/packages/own.moderpach.extinguish) e.g. from your Readme :smiley:
