### ISSUE TITLE
The Application is not working

### ISSUE THREAD

**Issue by FlyingCat9013** [Moderpach/Extinguish#16]
**Describe the bug**
I install the app, give all the permissions, give shizuku access, but the app just wont work as intended. When I press the extinguish button, nothing happens. Tried it multiple times but doesn't work.

**Log(If there is an exception notification)**
```
No notification 
```

**Environment**
 - Device: Motorola edge 40 neo
 - OS: MyUX, Android 14
 - Version 0.9.5.1

**Additional context**
None

**Comment by Moderpach** [comment]
That means Motorola change the hidden api behaviour in myui.
I can do nothing on shizuku layer.
I will explore xposed method in the future and that may solve the problem.
