### ISSUE TITLE
Volume buttons keep turning off screen even when settings are off 

### ISSUE THREAD

**Issue by PeterKW** [Moderpach/Extinguish#2]
![Screenshot_20240912-004248.png](https://github.com/user-attachments/assets/a4997657-c468-427b-bfff-ecaf8643db65)

**Comment by PeterKW** [comment]
![Screenshot_20240912-004606.png](https://github.com/user-attachments/assets/a217e193-be4c-4280-9207-cd74dc9384c1)

![Screenshot_20240912-004453.png](https://github.com/user-attachments/assets/b438ef7b-7ce5-4aed-be40-b32bb6686cca)

**Comment by PeterKW** [comment]
Anything else that I could try to stop the volume buttons toggling the screen?

**Comment by Moderpach** [comment]
Maybe you haven't restart extinguish service. The setting will take effect after restarting extinguish service2024年9月12日 上午7:47，Peter ***@***.***>写道：
Anything else that I could try to stop the volume buttons toggling the screen?

**Comment by PeterKW** [comment]
If you mean clicking stop service and then clicking start service with volume button option disabled then I have tried that unfortunately 

When I click my volume button the screen goes dark even if that setting is turned off 

Anything else that I could try? Stopping the service temporarily stops the screen going dark

Android 14

**Comment by Moderpach** [comment]
Ok, i'm sure it is a bug. It only happen when "Touch screen to turen it on" is on with solution "Shizuku | Set screen brightness to -1".

**Comment by Moderpach** [comment]
Fix in https://github.com/Moderpach/Extinguish/commit/ed4ad578c98bbf1e8277a80c215e198d426380fd
Try 0.9.3
