### ISSUE TITLE
Touchscreen works in Shizuku | Set screen power off mode

### ISSUE THREAD

**Issue by microspock** [Moderpach/Extinguish#3]
Hi,

Touchscreen works in Shizuku | Set screen power off mode,

I'm on samsung S23 Oneui 6.1.

It was already the case in 9.2, 9,1, and 9.0 version.

Best regards

**Comment by Moderpach** [comment]
Yes, that's right. I’m using the S23 too. It's a Samsung issue, and there's not much I can do about it.

**Comment by Moderpach** [comment]
That's why the description of solution has "Behavior may change due to customizations by the device manufacturer"

**Comment by microspock** [comment]
I was pretty sure it was Samsung only problem, thx for the confirmation.
