### ISSUE TITLE
Brightness Issue

### ISSUE THREAD

**Issue by KelvinCrag** [Moderpach/Extinguish#4]
I believe this app disrupted my brightness settings. Now, my phone's brightness won't increase much, and medium brightness appears low.

Can I undo the changes made by this app?

Device: Pixel 7 (Stock ROM)

**Comment by Moderpach** [comment]
Try rebooting your phone
If brightness setting is still broken, tell me again

**Comment by Moderpach** [comment]
Are you using "Shizuku | set screen brightness to -1"? "Shizuku | set screen power off" may has less brightness problem.

**Comment by KelvinCrag** [comment]
Thanks, it's working fine now.

**Comment by happmaoo** [comment]
> Are you using "Shizuku | set screen brightness to -1"? "Shizuku | set screen power off" may has less brightness problem.

how to do this ?

**Comment by Moderpach** [comment]
> > Are you using "Shizuku | set screen brightness to -1"? "Shizuku | set screen power off" may has less brightness problem.
> 
> how to do this ?

![Screenshot_20240923_133441_Extinguish](https://github.com/user-attachments/assets/15a6fb73-f39f-4d57-82e6-0124902c80a5)

here
