### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by K0-RR** [Moderpach/Extinguish#6]
Hi, is an app icon available (png, jpg, webp, svg) here?
I saw the app with it on F-droid, I wanted to add your app to alternativeto database.

**Comment by Moderpach** [comment]
![ExtiniguishLogo](https://github.com/user-attachments/assets/010dd90a-145b-4c22-a550-96e9c4e0db7a)

**Comment by K0-RR** [comment]
Thanks, though it's different from the one on izzyondroid repo (purple vs purple-red)
